USE
[master]
GO
CREATE
LOGIN [bdh] WITH PASSWORD=N'bdh', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [PointageBDH]
GO
CREATE
USER [bdh] FOR LOGIN [bdh]
GO
USE [PointageBDH]
GO
ALTER
ROLE [db_owner] ADD MEMBER [bdh]
GO